// The HUD's spatial sound for a sim event (extracted from Hud.playEventSfx and
// its three private helpers): positioned at the relevant entity so nearby
// players' and creatures' combat attenuates with distance and pans correctly.
// Personal/UI sounds stay on the sampled audio.* facade in handleEvents. All
// combat/spell/creature SFX route through playCombatSfx so the whole layer can
// be balanced with the single COMBAT_GAIN knob (kept under movement/ambience).
// The cue choices are the pure combat_sfx.ts mappings; this module only plays
// them and keeps the two sets the Hud prunes in reconcileSfx.
//
// Hud members are private, so the router takes the Hud untyped (the
// quest_event_router.ts shape); the members it reads are welded to hud.ts in
// tests/event_sfx_router.test.ts.

import { audio } from '../game/audio';
import { sfx } from '../game/sfx';
import type { Entity, SimEvent } from '../sim/types';
import type { IWorld } from '../world_api';
import {
  auraApplyCue,
  castCueForAbility,
  dispatchRaidCalloutSfx,
  groundTickAbilityCue,
  healAudioPlan,
  impactCueForDamage,
  mobVoiceActionForDamage,
  mobVoiceCueWithFallback,
  novaAbilityCue,
  playerSwingCueForDamage,
  playerVoiceCue,
  shouldPlayCombatImpactForTarget,
  shouldPlayCritSfxForTarget,
  shouldPlayMobVoiceSfxForEntity,
  spellFxCue,
} from './combat_sfx';
import { availableMobVoiceCue, sfxHasCue } from './hud_voice_cues';

// --- spatial sound-effect mapping (clips generated by scripts/gen_sfx.mjs;
// engine in src/game/sfx.ts) ------------------------------------------------
// One shared multiplier for the whole combat/spell/creature SFX layer, on top
// of each key's own resolved gain-map value. At 1.0 (unchanged) since the
// per-key computed gain ceilings (scripts/sfx/sfx_gain_ceiling.mjs) already
// carry each custom recording to its own safe maximum; lower this if the
// layer as a whole needs trimming back under movement/ambience again.
export const COMBAT_GAIN = 1.0;
export const TEMPORAL_CLOCK_GAIN = 0.72;

/** The private Hud members the router reads and writes. */
export interface EventSfxHost {
  readonly sim: Pick<IWorld, 'entities' | 'player' | 'playerId'>;
  /** Entity ids with a sustained cast-loop SFX playing, so reconcileSfx can
   *  stop loops for casters that left interest mid-channel. */
  readonly castLoopIds: Set<number>;
  /** Mob ids that already vocalized their aggro alert. */
  readonly mobAggroed: Set<number>;
}

/** One positioned combat/spell/creature cue, scaled by COMBAT_GAIN (Hud.combat
 *  before the extraction; the aura arm's Hourglass tick calls it too). */
export function playCombatSfx(
  key: string,
  x: number,
  y: number,
  z: number,
  gain: number,
  opts?: { rate?: number; cooldown?: number; jitter?: boolean },
): void {
  sfx.playAt(key, x, y, z, {
    gain: gain * COMBAT_GAIN,
    rate: opts?.rate,
    cooldown: opts?.cooldown,
    jitter: opts?.jitter,
  });
}

/** The spatial sound for one sim event, for everyone nearby. */
export function playEventSfx(h: EventSfxHost, ev: SimEvent): void {
  const sim = h.sim;
  switch (ev.type) {
    case 'damage': {
      const tgt = sim.entities.get(ev.targetId);
      if (!tgt) return;
      const tp = tgt.pos;
      const src = sim.entities.get(ev.sourceId) ?? null;
      const swing = playerSwingCueForDamage(ev, src);
      if (swing && src) {
        playCombatSfx(swing, src.pos.x, src.pos.y, src.pos.z, 1.0, {
          cooldown: 0.08,
        });
      }
      if ((ev.absorbed ?? 0) > 0 || ev.kind === 'block')
        playCombatSfx('combat_block', tp.x, tp.y, tp.z, 0.55);
      // The miss/dodge/resist/parry/evade "avoid" cues are interface feedback (they
      // report an outcome, not a world impact), so the Interface & Feedback Sounds
      // toggle silences them. The early return stays either way, so a muted avoid
      // never falls through to an impact sound.
      if (
        ev.kind === 'miss' ||
        ev.kind === 'dodge' ||
        ev.kind === 'resist' ||
        ev.kind === 'evade'
      ) {
        if (audio.feedbackEnabled) playCombatSfx('combat_dodge', tp.x, tp.y, tp.z, 0.5);
        return;
      }
      if (ev.kind === 'parry') {
        if (audio.feedbackEnabled) playCombatSfx('combat_parry', tp.x, tp.y, tp.z, 0.6);
        return;
      }
      if (src?.kind === 'mob') playAttackerSfx(h, src);
      // a struck mob vocalizes its aggro alert the first time it's engaged
      // (camp engage), whether you hit it or it hits you.
      if (tgt.kind === 'mob') ensureMobEngaged(h, tgt);
      const impact = impactCueForDamage(ev, tgt);
      if (shouldPlayCombatImpactForTarget(tgt)) {
        if (impact) playCombatSfx(impact, tp.x, tp.y, tp.z, 1.0, { cooldown: 0.05 });
      }
      if (ev.crit && shouldPlayCritSfxForTarget(tgt))
        playCombatSfx('combat_crit', tp.x, tp.y, tp.z, 1.0);
      // pain vocalization only on a crit, never on ordinary hits. Voiced per
      // the target's own authored gender (playerVoiceCue): a female look gets
      // the female takes, everything else keeps the shipped male ones.
      if (ev.crit && ev.targetId === sim.playerId) {
        const cue = playerVoiceCue(tgt?.modularAppearance, 'hurt', sfxHasCue);
        playCombatSfx(cue, tp.x, tp.y, tp.z, 1.0, { cooldown: 0.3 });
      } else {
        const mobAction = mobVoiceActionForDamage(ev, tgt);
        if (mobAction && shouldPlayMobVoiceSfxForEntity(tgt)) {
          const voice = mobVoiceCueWithFallback(
            tgt.templateId,
            mobAction,
            (key) => sfx.hasVariants(key),
            (key) => sfx.isBuffered(key),
          );
          if (voice) playCombatSfx(voice, tp.x, tp.y, tp.z, 1.0, { cooldown: 0.1 });
        }
      }
      return;
    }
    case 'castStart': {
      const ent = sim.entities.get(ev.entityId);
      // Chain Heal uses a custom one-shot healing cast clip (cast_chain_heal)
      // instead of the earthy nature cast loop its school would otherwise pick.
      if (ent && ev.ability === 'chain_heal') {
        playCombatSfx('cast_chain_heal', ent.pos.x, ent.pos.y, ent.pos.z, 1.0);
        return;
      }
      const key = castCueForAbility(ev.ability);
      if (ent && key) {
        sfx.loop(`cast:${ev.entityId}`, key, 1.0 * COMBAT_GAIN, ent.pos.x, ent.pos.y, ent.pos.z);
        h.castLoopIds.add(ev.entityId);
      }
      return;
    }
    case 'castStop':
      sfx.unloop(`cast:${ev.entityId}`, 0.2);
      h.castLoopIds.delete(ev.entityId);
      return;
    case 'varkhulCallout':
    case 'nythraxisCallout': {
      dispatchRaidCalloutSfx(
        ev,
        (entityId) => sim.entities.get(entityId),
        (cue, x, y, z, gain, opts) => playCombatSfx(cue, x, y, z, gain, opts),
      );
      return;
    }
    case 'spellfx': {
      if (ev.fx === 'temporalClock') {
        const source = sim.entities.get(ev.sourceId) ?? sim.entities.get(ev.targetId);
        if (source)
          playCombatSfx(
            'temporal_clock',
            source.pos.x,
            source.pos.y,
            source.pos.z,
            TEMPORAL_CLOCK_GAIN,
            {
              jitter: false,
            },
          );
        return;
      }
      const cue = spellFxCue(ev);
      const anchor = cue ? sim.entities.get(cue.anchorId) : null;
      if (cue && anchor) playCombatSfx(cue.key, anchor.pos.x, anchor.pos.y, anchor.pos.z, 1.0);
      return;
    }
    case 'spellfxAt': {
      // Meteor's landing recording is preloaded lazily (SFX_CLIPS entries
      // preload: 'lazy' by default), so a first-cast-of-session player can
      // hit the fx:'tick' below before the fetch+decode finishes and
      // playAt's 0.12s unbuffered-oneshot race drops it silently. The
      // meteorFall telegraph fires here about 2s before the ground tick
      // lands (effect_dispatch.ts), which is exactly enough lead time to
      // warm the buffer if we kick the preload off now.
      if (ev.fx === 'meteorFall') {
        sfx.preload('meteor');
        return;
      }
      // A ground-zone pulse (Consecration, Blizzard's damage tick, Meteor's
      // one delayed hit): a dedicated recording (Meteor) is the whole read;
      // every other zone stays silent here and keeps its procedural
      // VFX-synth voice (ability_sfx_coverage.ts).
      if (ev.fx === 'tick') {
        const tickKey = groundTickAbilityCue(ev.ability);
        if (tickKey) playCombatSfx(tickKey, ev.x, sim.player.pos.y, ev.z, 1.0, { cooldown: 0.08 });
        return;
      }
      // Ground-anchored bursts (ground-target detonations, the citadel's Blood
      // Orb flare, the portcullis release nova) were silent: give novas the
      // shared burst layered with a school-flavored impact, so the orb's fire
      // flare reads differently from the gate's holy release. The listener is
      // on the same floor, so the player's own y is the right height anchor.
      const y = sim.player.pos.y;
      // A fixed custom recording (rift mechanics: riftFx in src/sim/rift/fx.ts)
      // replaces the generic nova/burst sound entirely, for both fx variants,
      // not just nova.
      if (ev.sfxKey) {
        playCombatSfx(ev.sfxKey, ev.x, y, ev.z, 1.0, { cooldown: 0.08 });
        return;
      }
      if (ev.fx !== 'nova') return;
      // A per-ability nova recording is the whole read on the aimed path
      // too, at the same 1.0 the entity-anchored spellfx path plays it;
      // the generic burst keeps its school-flavored layer.
      const novaKey = novaAbilityCue(ev.ability);
      if (novaKey !== 'spell_nova') {
        playCombatSfx(novaKey, ev.x, y, ev.z, 1.0, { cooldown: 0.08 });
        return;
      }
      playCombatSfx('spell_nova', ev.x, y, ev.z, 0.6, { cooldown: 0.08 });
      playCombatSfx(`impact_${ev.school}`, ev.x, y, ev.z, 0.5, { rate: 0.8, cooldown: 0.08 });
      return;
    }
    case 'heal':
    case 'heal2': {
      const tgt = sim.entities.get(ev.targetId);
      if (!tgt) return;
      const plan = healAudioPlan(ev);
      if (!plan) return;
      playCombatSfx(plan.cue, tgt.pos.x, tgt.pos.y, tgt.pos.z, plan.gain, { cooldown: 0.1 });
      return;
    }
    case 'aura': {
      if (ev.targetId !== sim.playerId) return; // only your own buffs/debuffs, else it's spammy
      const target = sim.entities.get(ev.targetId);
      const aura = ev.gained
        ? (target?.auras.find((entry) => entry.name === ev.name) ?? null)
        : null;
      const cue = auraApplyCue(ev, aura);
      if (!cue) return;
      const p = sim.player.pos;
      playCombatSfx(cue, p.x, p.y, p.z, 1.0, {
        cooldown: 0.1,
      });
      return;
    }
    case 'death': {
      sfx.unloop(`cast:${ev.entityId}`, 0);
      h.castLoopIds.delete(ev.entityId);
      const ent = sim.entities.get(ev.entityId);
      if (!ent) return;
      const p = ent.pos;
      if (ent.kind === 'mob') {
        h.mobAggroed.delete(ev.entityId);
        const voice = availableMobVoiceCue(ent.templateId, 'death');
        if (voice && shouldPlayMobVoiceSfxForEntity(ent)) playCombatSfx(voice, p.x, p.y, p.z, 1.0);
      } else if (ent.kind === 'player' && ev.entityId !== sim.playerId) {
        // This branch is OTHER players dying; your OWN character's death
        // sound is a separate trigger site, audio.playerDeath() in
        // src/game/audio.ts. Voiced per the dying player's own authored
        // gender, which rides their identity wire, so a female character you
        // watch die sounds female to you.
        const cue = playerVoiceCue(ent.modularAppearance, 'death', sfxHasCue);
        playCombatSfx(cue, p.x, p.y, p.z, 1.0);
      }
      return;
    }
  }
}

// First contact with a mob (it hits you, or you hit it) plays its aggro alert
// once: the "engage" sound. Returns true if this call fired it. Cleared on
// death / when the mob leaves interest (reconcileSfx).
function ensureMobEngaged(h: EventSfxHost, mob: Entity): boolean {
  if (h.mobAggroed.has(mob.id)) return false;
  h.mobAggroed.add(mob.id);
  const voice = availableMobVoiceCue(mob.templateId, 'aggro');
  if (voice && shouldPlayMobVoiceSfxForEntity(mob))
    playCombatSfx(voice, mob.pos.x, mob.pos.y, mob.pos.z, 1.0);
  return true;
}

// Attacker side of a mob damage event: it roars on engage, then grunts on
// subsequent strikes. Player swings are resolved earlier from the damage event.
function playAttackerSfx(h: EventSfxHost, src: Entity): void {
  if (src.kind === 'mob') {
    if (ensureMobEngaged(h, src)) return; // just fired the aggro alert
    const voice = availableMobVoiceCue(src.templateId, 'attack');
    if (voice && shouldPlayMobVoiceSfxForEntity(src)) {
      playCombatSfx(voice, src.pos.x, src.pos.y, src.pos.z, 1.0, {
        cooldown: 0.25,
      });
      // Warm the crit-only hurt cue alongside the frequently-played attack
      // bark, so it is resident well before a crit could ever need it. Gated
      // the same as the play above (a muted Nythraxis mob never plays it)
      // and short-circuited once warm so this doesn't re-scan every hit.
      const hurtVoice = availableMobVoiceCue(src.templateId, 'hurt');
      if (hurtVoice && !sfx.isBuffered(hurtVoice)) sfx.preload(hurtVoice);
    }
  }
}
